Esto merece un copyRight, no?
gabo-hacStyle/gabs pull request #9
Opened 2020-10-10 03:04 UTC by gabsnotashamed

Un copyright proveera beneficios: 

1. Nadie se va a copiar 
2.  Muestra profesionalismo
Y otras cosas más. 
**Por eso considere añadir el copy de Gabs. Nuestro buen comienzo**

2020-10-10 20:51 UTC, gabo-hacStyle commented
Le haré pull y lo revisaré. Luego confirmo el merge

2020-10-10 22:13 UTC, gabo-hacStyle requested changes
Entonces busquemos otro tipo de letra que combine con la del header. Así podremos merge la rama del footer (cambios letra )y la de el adding-hovers (cambios letra para main-tiles).
Luego podremos merge them con Master.

> Never stop looking for wisdom from the Lord our God

2020-10-10 22:13 UTC, gabo-hacStyle commented on index.html
> +	    <div class="centered-content">&copy;GABS</div>
Hola. Gracias por la sugerencia. obviamente lo vamos a dejar. Sin embargo, quiero que el tipo de letra sea cambiado: Tanto en el footer de &copy, como en las main-tiles.
**Tiene que ser más paecido, que sea más cerca de cómo es la otra -- del header**.

> Never stop looking for the wisdom of the Lord our  God

2020-10-11 03:07 UTC, gabsnotashamed commented on index.html
> +	    <div class="centered-content">&copy;GABS</div>
Ok. Trabajaré en ello

2020-10-12 21:51 UTC, closed without merging